import type { HeroContent } from "@/types/hero";

/**
 * Hero layout aligned to Figma node 981:938 (Frame 45, 1440 × 1168).
 * Positions are % of artboard; rotations match the Figma mockup.
 */
export const heroContent: HeroContent = {
  artboard: {
    width: 1440,
    height: 1168,
  },
  headlines: [
    {
      id: "world-full",
      text: "THE WORLD IS FULL OF",
      left: 17.569,
      top: 13.185,
      width: 21.613,
      variant: "statement",
    },
    {
      id: "unfinished-ideas",
      text: "UNFINISHED IDEAS",
      left: 55.069,
      top: 27.312,
      width: 14.653,
      variant: "statement",
    },
    {
      id: "frustrating",
      text: "& FRUSTRATING EXPERIENCES",
      left: 24.028,
      top: 46.147,
      width: 21.319,
      variant: "statement",
    },
    {
      id: "contact",
      text: "Smriti.205@",
      left: 10.069,
      top: 69.178,
      variant: "contact",
    },
    {
      id: "script-line",
      text: "I design the path",
      left: 66.736,
      top: 55.5,
      width: 13.333,
      variant: "script",
    },
    {
      id: "seamless",
      text: "THAT MAKE THEM SEAMLESS",
      left: 66.736,
      top: 62.5,
      width: 14.236,
      variant: "tagline",
    },
  ],
  collage: [
    {
      id: "starry-night",
      alt: "The Starry Night print",
      src: "/Hero/hero-image-painting.png",
      left: 7.986,
      top: 5.5,
      width: 7.703,
      height: 10.5,
      placeholderColor: "#4a6fa5",
    },
    {
      id: "desk-lamp",
      alt: "Green desk lamp",
      src: "/Hero/hero-image-lamp.png",
      left: 6.5,
      top: 26.5,
      width: 14.5,
      height: 33.6,
      placeholderColor: "#6b8f71",
    },
    {
      id: "headphones",
      alt: "Over-ear headphones",
      src: "/Hero/hero-image-headphone.png",
      left: 17,
      top: 26,
      width: 9.5,
      height: 10,
      placeholderColor: "#d1d5db",
      rotation: -15,
    },
    {
      id: "vinyl-record",
      alt: "Vinyl record",
      src: "/Hero/hero-image-disk.png",
      left: 24,
      top: 21,
      width: 9.5,
      height: 18,
      placeholderColor: "#1a1a1a",
    },
    {
      id: "sprint-book",
      alt: "SPRINT book",
      src: "/Hero/hero-image-book.png",
      left: 48.6,
      top: 4.45,
      width: 7.703,
      height: 21,
      placeholderColor: "#e8c547",
      rotation: 3,
    },
    {
      id: "coffee-croissant",
      alt: "Coffee and croissant",
      src: "/Hero/hero-image-coffee.png",
      left: 57.002,
      top: 4.45,
      width: 12.604,
      height: 13.65,
      placeholderColor: "#c4a882",
    },
    {
      id: "folder-icons",
      alt: "Design folder with icons",
      src: "/Hero/hero-image-folder.png",
      left: 67.506,
      top: 10.75,
      width: 12.604,
      height: 21,
      placeholderColor: "#6ea5e8",
    },
    {
      id: "crt-monitor",
      alt: "Vintage computer monitor",
      src: "/Hero/hero-image-computer.png",
      left: 67.222,
      top: 33.39,
      width: 8.611,
      height: 10.702,
      placeholderColor: "#d9d4c7",
    },
    {
      id: "stamps",
      alt: "Postage stamps",
      src: "/Hero/hero-image-stamps.png",
      left: 50,
      top: 58,
      width: 12.5,
      height: 13.5,
      placeholderColor: "#f0ebe3",
      rotation: 12,
    },
    {
      id: "plant",
      alt: "Potted plant",
      src: "/Hero/hero-image-plant.png",
      left: 11.487,
      top: 63.25,
      width: 10.504,
      height: 21,
      placeholderColor: "#8fbc8f",
    },
    {
      id: "blue-note",
      alt: "To-do sticky note",
      src: "/Hero/hero-image-blue note.png",
      left: 36,
      top: 68,
      width: 5.5,
      height: 7,
      placeholderColor: "#b8d4f0",
      rotation: -6,
    },
    {
      id: "pink-note",
      alt: "Review sticky note",
      src: "/Hero/hero-image-red note.png",
      left: 32,
      top: 74,
      width: 5.5,
      height: 7,
      placeholderColor: "#f4b4c4",
      rotation: 5,
    },
    {
      id: "instax-camera",
      alt: "Instant camera",
      src: "/Hero/hero-image-camera.png",
      left: 84,
      top: 80,
      width: 5,
      height: 8.5,
      placeholderColor: "#a8d5cf",
    },
    {
      id: "journal",
      alt: "Leather journal",
      src: "/Hero/hero-image-journal.png",
      left: 74,
      top: 78,
      width: 11.5,
      height: 21,
      placeholderColor: "#ac7f5e",
      rotation: 10,
    },
    {
      id: "cursor",
      alt: "",
      src: "/Hero/hero-image-cursor.png",
      left: 84.5,
      top: 63.5,
      width: 1.667,
      height: 2.055,
      placeholderColor: "transparent",
    },
  ],
  grid: {
    left: 7.986,
    top: 5.5,
    width: 84.028,
    height: 84,
    cellSize: 55,
  },
  dock: {
    left: 30.625,
    top: 87.159,
    items: [
      {
        id: "puzzle",
        label: "Extensions",
        href: "#",
        icon: "puzzle",
      },
      {
        id: "brush",
        label: "Tools",
        href: "#",
        icon: "brush",
      },
    ],
  },
};
