import type { HeroContent } from "@/types/hero";

/**
 * Figma node 981:938 — x/y/width/height in px on a 1440 × 1168 artboard.
 * Source of truth for Hero layout. Prioritize visual accuracy: sync from Figma, do not estimate.
 */
export const heroContent: HeroContent = {
  artboard: {
    width: 1440,
    height: 1168,
  },
  headlines: [
    {
      id: "world-full",
      text: "THE WORLD IS FULL OF",
      x: 253,
      y: 154,
      width: 311,
      lines: [
        { text: "THE WORLD IS" },
        { text: "FULL OF" },
      ],
      variant: "statement",
    },
    {
      id: "unfinished-ideas",
      text: "UNFINISHED IDEAS",
      x: 793,
      y: 319,
      width: 211,
      align: "left",
      lines: [
        { text: "UNFINISHED" },
        { text: "IDEAS", width: 165 },
      ],
      variant: "statement",
    },
    {
      id: "frustrating",
      text: "& FRUSTRATING EXPERIENCES",
      x: 346,
      y: 539,
      width: 307,
      align: "center",
      lines: [{ text: "& FRUSTRATING" }, { text: "EXPERIENCES" }],
      variant: "statement",
    },
    {
      id: "contact",
      text: "Smriti.205@",
      x: 145,
      y: 808,
      width: 105,
      variant: "contact",
    },
    {
      id: "script-line",
      text: "I design the path",
      x: 961,
      y: 668,
      width: 135,
      variant: "script",
    },
    {
      id: "seamless",
      text: "THAT MAKE THEM SEAMLESS",
      x: 961,
      y: 708,
      width: 205,
      align: "left",
      lines: [
        { text: "THAT MAKE" },
        { text: "THEM" },
        { text: "SEAMLESS" },
      ],
      variant: "statement",
    },
  ],
  collage: [
    {
      id: "starry-night",
      alt: "The Starry Night print",
      src: "/Hero/hero-image-painting.png",
      x: 65,
      y: 73,
      width: 176,
      height: 141,
      placeholderColor: "#4a6fa5",
    },
    {
      id: "desk-lamp",
      alt: "Green desk lamp",
      src: "/Hero/hero-image-lamp.png",
      x: 73,
      y: 308,
      width: 234,
      height: 296,
      placeholderColor: "#6b8f71",
    },
    {
      id: "headphones",
      alt: "Over-ear headphones",
      src: "/Hero/hero-image-headphone.png",
      x: 280,
      y: 308,
      width: 110,
      height: 112,
      placeholderColor: "#d1d5db",
    },
    {
      id: "vinyl-record",
      alt: "Vinyl record",
      src: "/Hero/hero-image-disk.png",
      x: 495,
      y: 262,
      width: 193,
      height: 183,
      placeholderColor: "#1a1a1a",
    },
    {
      id: "sprint-book",
      alt: "SPRINT book",
      src: "/Hero/hero-image-book.png",
      x: 799,
      y: 148,
      width: 124,
      height: 154,
      placeholderColor: "#e8c547",
    },
    {
      id: "coffee-croissant",
      alt: "Coffee and croissant",
      src: "/Hero/hero-image-coffee.png",
      x: 944,
      y: 144,
      width: 200,
      height: 109,
      placeholderColor: "#c4a882",
    },
    {
      id: "folder-icons",
      alt: "Design folder",
      src: "/Hero/hero-image-folder.png",
      x: 1174,
      y: 256,
      width: 96,
      height: 90,
      placeholderColor: "#6ea5e8",
    },
    {
      id: "figma-icon",
      alt: "Figma",
      src: "/Hero/hero-image-figma.png",
      x: 1202,
      y: 218,
      width: 57,
      height: 57,
      placeholderColor: "transparent",
    },
    {
      id: "claude-icon",
      alt: "Claude",
      src: "/Hero/hero-image-claude.png",
      x: 1161,
      y: 240,
      width: 61,
      height: 61,
      placeholderColor: "transparent",
    },
    {
      id: "crt-monitor",
      alt: "Vintage computer monitor",
      src: "/Hero/hero-image-computer.png",
      x: 968,
      y: 390,
      width: 124,
      height: 125,
      placeholderColor: "#d9d4c7",
    },
    {
      id: "plant",
      alt: "Potted plant",
      src: "/Hero/hero-image-plant.png",
      x: 237,
      y: 662,
      width: 127,
      height: 141,
      placeholderColor: "#8fbc8f",
    },
    {
      id: "blue-note",
      alt: "To-do sticky note",
      src: "/Hero/hero-image-blue note.png",
      x: 418,
      y: 761,
      width: 90,
      height: 93,
      placeholderColor: "#b8d4f0",
    },
    {
      id: "pink-note",
      alt: "Review sticky note",
      src: "/Hero/hero-image-red note.png",
      x: 472.88,
      y: 689,
      width: 90,
      height: 93,
      placeholderColor: "#f4b4c4",
    },
    {
      id: "stamps",
      alt: "Postage stamps",
      src: "/Hero/hero-image-stamps.png",
      x: 721,
      y: 518,
      width: 222.98,
      height: 202.36,
      placeholderColor: "#f0ebe3",
    },
    {
      id: "instax-camera",
      alt: "Instant camera",
      src: "/Hero/hero-image-camera.png",
      x: 1112,
      y: 556,
      width: 103,
      height: 109,
      placeholderColor: "#a8d5cf",
    },
    {
      id: "journal",
      alt: "Leather journal",
      src: "/Hero/hero-image-journal.png",
      x: 1237,
      y: 748,
      width: 81,
      height: 110,
      placeholderColor: "#ac7f5e",
    },
    {
      id: "mouse-arrow",
      alt: "",
      src: "/Hero/hero-image-mousecursor.png",
      x: 1133,
      y: 840,
      width: 82,
      height: 110,
      placeholderColor: "transparent",
    },
    {
      id: "cursor",
      alt: "",
      src: "/Hero/hero-image-cursor.png",
      x: 1223,
      y: 246,
      width: 54,
      height: 49,
      placeholderColor: "transparent",
    },
  ],
  grid: {
    x: 115,
    y: 87,
    width: 1210,
    height: 771,
    cellSize: 55,
    cutoutShape: {
      x: 115,
      y: 143,
      width: 1210,
      height: 714,
    },
  },
  dock: {
    x: 656,
    y: 890,
    items: [
      {
        id: "puzzle",
        label: "Chaos mode on",
        href: "#",
        icon: "puzzle",
        mode: "chaos",
        tooltip: {
          text: "Chaos mode on",
        },
      },
      {
        id: "brush",
        label: "Clean mode on",
        href: "#",
        icon: "brush",
        mode: "clean",
        tooltip: {
          text: "Clean mode on",
        },
      },
    ],
  },
};
