import type { HeroContent } from "@/types/hero";

/** Positions derived from Figma Frame 45 (902:10232) — 1440 × 1168 artboard */
export const heroContent: HeroContent = {
  artboard: {
    width: 1440,
    height: 1168,
  },
  headlines: [
    {
      id: "world-full",
      text: "THE WORLD IS FULL OF",
      left: 17.569,
      top: 13.183,
      width: 21.613,
      variant: "statement",
    },
    {
      id: "unfinished-ideas",
      text: "UNFINISHED IDEAS",
      left: 55.069,
      top: 27.311,
      width: 14.653,
      variant: "statement",
    },
    {
      id: "frustrating",
      text: "& FRUSTRATING EXPERIENCES",
      left: 24.028,
      top: 46.151,
      width: 21.319,
      variant: "statement",
    },
    {
      id: "contact",
      text: "Smriti.205@",
      left: 10.069,
      top: 69.178,
      variant: "contact",
    },
    {
      id: "script-line",
      text: "I design the path",
      left: 66.736,
      top: 57.192,
      width: 13.333,
      variant: "script",
    },
    {
      id: "seamless",
      text: "THAT MAKE THEM SEAMLESS",
      left: 66.736,
      top: 60.616,
      width: 14.236,
      variant: "tagline",
    },
  ],
  collage: [
    {
      id: "polaroid-top",
      alt: "Polaroid photo",
      left: 38.194,
      top: 14.126,
      width: 7.639,
      height: 9.589,
      placeholderColor: "#e8e4dc",
      rotation: -6,
    },
    {
      id: "accent-top-right",
      alt: "Decorative object",
      left: 80.625,
      top: 20.548,
      width: 4.236,
      height: 5.222,
      placeholderColor: "#d4cfc4",
    },
    {
      id: "object-upper-right",
      alt: "Decorative object",
      left: 81.528,
      top: 21.918,
      width: 6.667,
      height: 7.705,
      placeholderColor: "#c8c9c4",
    },
    {
      id: "gemini-object",
      alt: "Decorative object",
      left: 67.222,
      top: 33.39,
      width: 8.611,
      height: 10.702,
      placeholderColor: "#ebeae7",
    },
    {
      id: "journal-left",
      alt: "Journal spread",
      left: 16.458,
      top: 56.679,
      width: 8.819,
      height: 12.071,
      placeholderColor: "#e4e4e3",
      rotation: 4,
    },
    {
      id: "cards-mid",
      alt: "Photo cards",
      left: 29.028,
      top: 65.154,
      width: 6.25,
      height: 7.962,
      placeholderColor: "#f0f4fa",
    },
    {
      id: "cards-mid-2",
      alt: "Photo cards",
      left: 32.839,
      top: 58.99,
      width: 6.25,
      height: 7.962,
      placeholderColor: "#f5f8ff",
      rotation: 8,
    },
    {
      id: "object-lower-right",
      alt: "Decorative object",
      left: 78.681,
      top: 71.918,
      width: 5.694,
      height: 9.418,
      placeholderColor: "#d9d5cb",
    },
  ],
  grid: {
    left: 7.986,
    top: 73.459,
    width: 84.028,
    height: 66.011,
    cellSize: 55,
  },
  dock: {
    left: 30.625,
    top: 87.159,
    width: 38.736,
    height: 6.312,
    items: [
      {
        id: "linkedin",
        label: "LinkedIn",
        href: "https://linkedin.com",
        kind: "social",
      },
      {
        id: "dribbble",
        label: "Dribbble",
        href: "https://dribbble.com",
        kind: "social",
      },
      {
        id: "behance",
        label: "Behance",
        href: "https://behance.net",
        kind: "social",
      },
      {
        id: "instagram",
        label: "Instagram",
        href: "https://instagram.com",
        kind: "social",
      },
      {
        id: "whatsapp",
        label: "WhatsApp",
        href: "https://wa.me",
        kind: "social",
      },
      {
        id: "resume",
        label: "Resume",
        href: "/resume",
        kind: "action",
      },
      {
        id: "contact",
        label: "Contact",
        href: "mailto:smriti.205@gmail.com",
        kind: "action",
      },
    ],
  },
};
